---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minio-external-secret
  namespace: backup-system
spec:
  refreshInterval: 15m
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-secret-store

  target:
    name: minio-secret
    creationPolicy: Owner
    template:
      data:
        # MinIO chart v17 expects these key names
        root-user: "{{ .MINIO_ROOT_USER }}"
        root-password: "{{ .MINIO_ROOT_PASSWORD }}"

  data:
    - secretKey: MINIO_ROOT_USER
      remoteRef:
        key: MINIO_ROOT_USER
    - secretKey: MINIO_ROOT_PASSWORD
      remoteRef:
        key: MINIO_ROOT_PASSWORD
