---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-backup-external-secret
  namespace: sveltehr-prod
spec:
  refreshInterval: 15m
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-secret-store

  target:
    name: postgres-backup-secret
    creationPolicy: Owner
    template:
      data:
        # CloudNativePG expects these key names for S3 credentials
        ACCESS_KEY_ID: "{{ .POSTGRES_BACKUP_ACCESS_KEY }}"
        SECRET_ACCESS_KEY: "{{ .POSTGRES_BACKUP_SECRET_KEY }}"

  data:
    - secretKey: POSTGRES_BACKUP_ACCESS_KEY
      remoteRef:
        key: POSTGRES_BACKUP_ACCESS_KEY
    - secretKey: POSTGRES_BACKUP_SECRET_KEY
      remoteRef:
        key: POSTGRES_BACKUP_SECRET_KEY
