/**
 * Migration File Writer (T031)
 *
 * Writes migration files with standardized metadata headers.
 * Supports both forward and rollback migration generation.
 */

import { writeFile, mkdir } from 'fs/promises';
import { join, dirname } from 'path';
import type { MigrationMetadata } from '../types/migration';

/**
 * Generates a migration filename following the naming pattern.
 *
 * Pattern: YYYYMMDD_NNN_description.sql
 *
 * @param date - Date string in YYYYMMDD format
 * @param sequence - Three-digit sequence number (001-999)
 * @param description - Snake_case description
 * @returns Migration filename
 */
export function generateFilename(
	date: string,
	sequence: number,
	description: string
): string {
	const paddedSequence = String(sequence).padStart(3, '0');
	const sanitizedDescription = description
		.toLowerCase()
		.replace(/[^a-z0-9_]/g, '_')
		.replace(/_+/g, '_')
		.replace(/^_|_$/g, '');

	return `${date}_${paddedSequence}_${sanitizedDescription}.sql`;
}

/**
 * Adds metadata header to SQL content.
 *
 * Header format:
 * -- Migration: [AUTO-GENERATED] Description
 * -- Created: ISO-8601 timestamp
 * -- Source: Schema drift detection
 * -- Affected: table/column names
 * -- Reason: missing_table | extra_column | etc.
 * -- Requires Review: YES
 *
 * @param sql - SQL content to add header to
 * @param metadata - Migration metadata
 * @returns SQL with header prepended
 */
export function addMetadataHeader(sql: string, metadata: MigrationMetadata): string {
	const headerLines: string[] = [
		`-- Migration: ${metadata.isAutoGenerated ? '[AUTO-GENERATED] ' : ''}${metadata.description}`,
		`-- Created: ${metadata.createdAt}`,
		`-- Source: ${metadata.source}`,
		`-- Affected: ${metadata.affectedObjects.join(', ')}`,
		`-- Reason: ${metadata.reason || 'manual'}`,
		`-- Requires Review: ${metadata.requiresReview ? 'YES' : 'NO'}`
	];

	// Add warnings if present
	if (metadata.warnings && metadata.warnings.length > 0) {
		headerLines.push('--');
		headerLines.push('-- WARNINGS:');
		for (const warning of metadata.warnings) {
			headerLines.push(`--   - ${warning}`);
		}
	}

	// Add manual steps if present
	if (metadata.manualSteps && metadata.manualSteps.length > 0) {
		headerLines.push('--');
		headerLines.push('-- MANUAL STEPS REQUIRED:');
		for (const step of metadata.manualSteps) {
			headerLines.push(`--   - ${step}`);
		}
	}

	headerLines.push('--');

	return headerLines.join('\n') + '\n\n' + sql;
}

/**
 * Writes a migration file to disk with metadata header.
 *
 * Creates parent directories if they don't exist.
 *
 * @param filepath - Full path to migration file
 * @param sql - SQL content (will be wrapped with header)
 * @param metadata - Migration metadata for header
 * @returns Promise that resolves when file is written
 */
export async function writeMigrationFile(
	filepath: string,
	sql: string,
	metadata: MigrationMetadata
): Promise<void> {
	// Ensure parent directory exists
	const dir = dirname(filepath);
	await mkdir(dir, { recursive: true });

	// Add metadata header to SQL
	const sqlWithHeader = addMetadataHeader(sql, metadata);

	// Write file
	await writeFile(filepath, sqlWithHeader, 'utf-8');
}

/**
 * Writes both forward and rollback migration files.
 *
 * @param basePath - Base directory for migration files
 * @param filename - Base filename (without .sql extension)
 * @param forwardSql - Forward migration SQL
 * @param rollbackSql - Rollback migration SQL (nullable)
 * @param metadata - Migration metadata
 * @returns Promise with paths to written files
 */
export async function writeMigrationPair(
	basePath: string,
	filename: string,
	forwardSql: string,
	rollbackSql: string | null,
	metadata: MigrationMetadata
): Promise<{
	forwardPath: string;
	rollbackPath: string | null;
}> {
	// Write forward migration
	const forwardPath = join(basePath, `${filename}.sql`);
	await writeMigrationFile(forwardPath, forwardSql, metadata);

	// Write rollback migration if provided
	let rollbackPath: string | null = null;
	if (rollbackSql) {
		rollbackPath = join(basePath, `${filename}.rollback.sql`);
		const rollbackMetadata: MigrationMetadata = {
			...metadata,
			description: `Rollback: ${metadata.description}`,
			source: `Rollback for ${metadata.source}`
		};
		await writeMigrationFile(rollbackPath, rollbackSql, rollbackMetadata);
	}

	return { forwardPath, rollbackPath };
}

/**
 * Generates a standardized migration filename with current date.
 *
 * @param sequence - Migration sequence number
 * @param description - Human-readable description
 * @returns Migration filename with today's date
 */
export function generateMigrationFilename(sequence: number, description: string): string {
	const today = new Date().toISOString().split('T')[0].replace(/-/g, '');
	return generateFilename(today, sequence, description);
}
