---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: alertmanager
  namespace: monitoring
  annotations:
    # Tailscale ingress configuration
    tailscale.com/funnel: 'false' # Private Tailnet access only
    tailscale.com/hostname: 'alertmanager' # Will be alertmanager.your-tailnet.ts.net
spec:
  ingressClassName: tailscale
  defaultBackend:
    service:
      name: kube-prometheus-stack-alertmanager
      port:
        number: 9093
  tls:
    - hosts:
        - alertmanager
