apiVersion: v1
kind: ConfigMap
metadata:
  name: sveltehr-config
  namespace: { { .Values.global.namespace } }
data:
  POSTGRES_DB: { { .Values.config.POSTGRES_DB | quote } }
  POSTGRES_USER: { { .Values.config.POSTGRES_USER | quote } }
  NODE_ENV: { { .Values.config.NODE_ENV | quote } }
  LOG_LEVEL: { { .Values.config.LOG_LEVEL | quote } }
