{{- if and .Values.monitoring .Values.monitoring.enabled -}}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.backend.name }}-monitor
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.backend.name }}
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: {{ .Values.backend.name }}
  endpoints:
    - port: http
      path: /metrics
      interval: {{ .Values.monitoring.scrapeInterval }}
      scrapeTimeout: {{ .Values.monitoring.scrapeTimeout }}

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.frontend.name }}-monitor
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.frontend.name }}
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: {{ .Values.frontend.name }}
  endpoints:
    - port: http
      path: /metrics
      interval: {{ .Values.monitoring.scrapeInterval }}
      scrapeTimeout: {{ .Values.monitoring.scrapeTimeout }}
{{- end }}
