{{- if and .Values.backend .Values.backend.enabled -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backend.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.backend.name }}
    component: graphql-api
  annotations:
    {{- if .Values.monitoring.enabled }}
    prometheus.io/scrape: "true"
    prometheus.io/port: {{ .Values.backend.service.port | quote }}
    prometheus.io/path: "/metrics"
    {{- end }}
    {{- with .Values.backend.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    app: {{ .Values.backend.name }}
  ports:
    - name: http
      port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.targetPort }}
      protocol: TCP
  type: {{ .Values.backend.service.type }}
{{- end }}

{{- if and .Values.frontend .Values.frontend.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.frontend.name }}
    component: web-ui
  annotations:
    {{- if .Values.monitoring.enabled }}
    prometheus.io/scrape: "true"
    prometheus.io/port: {{ .Values.frontend.service.port | quote }}
    prometheus.io/path: "/metrics"
    {{- end }}
    {{- if .Values.frontend.tailscale.enabled }}
    tailscale.com/expose: "true"
    tailscale.com/hostname: {{ .Values.frontend.tailscale.hostname | quote }}
    {{- end }}
    {{- with .Values.frontend.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    app: {{ .Values.frontend.name }}
  ports:
    - name: http
      port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.targetPort }}
      protocol: TCP
  type: {{ .Values.frontend.service.type }}
{{- end }}
