<script lang="ts">
	import { invalidate } from '$app/navigation';
	import { page } from '$app/stores';
	import { Card } from '$lib/components/ui/card';
	import { Badge } from '$lib/components/ui/badge';
	import { Button } from '$lib/components/ui/button';
	import { Alert, AlertDescription } from '$lib/components/ui/alert';
	import {
		Select,
		SelectContent,
		SelectItem,
		SelectTrigger,
		SelectValue
	} from '$lib/components/ui/select';
	import * as Tabs from '$lib/components/ui/tabs';
	import {
		FileText,
		Download,
		Calendar,
		Clock,
		User,
		AlertCircle,
		CheckCircle,
		Shield,
		FileSpreadsheet,
		RefreshCw
	} from '@lucide/svelte';

	let { data } = $props();

	let selectedReportType = $state(data.filters?.reportType || '');
	let refreshing = $state(false);

	let reports = $derived(data.reports || []);
	let schedules = $derived(data.schedules || []);
	let selectedReport = $derived(data.selectedReport);

	const reportTypes = [
		{ value: '', label: 'All Reports' },
		{ value: 'SOX', label: 'SOX Compliance' },
		{ value: 'GDPR', label: 'GDPR Compliance' },
		{ value: 'SOC2', label: 'SOC2 Compliance' },
		{ value: 'DataChanges', label: 'Data Changes' },
		{ value: 'UserActivity', label: 'User Activity' },
		{ value: 'AccessLog', label: 'Access Log' }
	];

	function getStatusVariant(
		status: string
	): 'default' | 'outline' | 'secondary' | 'destructive' {
		switch (status?.toLowerCase()) {
			case 'completed':
				return 'default';
			case 'failed':
				return 'destructive';
			case 'in_progress':
				return 'secondary';
			default:
				return 'outline';
		}
	}

	function getReportTypeVariant(
		reportType: string
	): 'default' | 'outline' | 'secondary' | 'destructive' {
		switch (reportType) {
			case 'SOX':
			case 'SOC2':
				return 'destructive';
			case 'GDPR':
				return 'secondary';
			default:
				return 'outline';
		}
	}

	function formatDate(dateStr: string): string {
		if (!dateStr) return 'N/A';
		return new Date(dateStr).toLocaleString();
	}

	function formatDateShort(dateStr: string): string {
		if (!dateStr) return 'N/A';
		return new Date(dateStr).toLocaleDateString();
	}

	async function handleRefresh() {
		refreshing = true;
		await invalidate('app:compliance');
		refreshing = false;
	}

	function handleReportTypeChange(value: string | undefined) {
		if (value === undefined) return;
		const url = new URL($page.url);
		if (value) {
			url.searchParams.set('reportType', value);
		} else {
			url.searchParams.delete('reportType');
		}
		window.location.href = url.toString();
	}
</script>

<div class="space-y-6">
	<!-- Header -->
	<div class="flex items-center justify-between">
		<div>
			<h1 class="text-3xl font-bold tracking-tight">Compliance Reports</h1>
			<p class="text-muted-foreground">Monitor compliance and regulatory reports</p>
		</div>
		<Button onclick={handleRefresh} disabled={refreshing}>
			<RefreshCw class="h-4 w-4 mr-2 {refreshing ? 'animate-spin' : ''}" />
			Refresh
		</Button>
	</div>

	{#if data.error}
		<Alert variant="destructive">
			<AlertCircle class="h-4 w-4" />
			<AlertDescription>{data.error}</AlertDescription>
		</Alert>
	{/if}

	<!-- Single Report Detail View -->
	{#if selectedReport}
		<Card class="p-6">
			<div class="space-y-6">
				<div class="flex items-start justify-between">
					<div>
						<div class="flex items-center gap-3 mb-2">
							<Badge variant={getReportTypeVariant(selectedReport.reportType)}>
								{selectedReport.reportType}
							</Badge>
							<Badge variant={getStatusVariant(selectedReport.status)}>
								{selectedReport.status}
							</Badge>
						</div>
						<h2 class="text-2xl font-bold">Report #{selectedReport.id}</h2>
						<p class="text-sm text-muted-foreground mt-1">
							Period: {formatDateShort(selectedReport.periodStart)} - {formatDateShort(
								selectedReport.periodEnd
							)}
						</p>
					</div>
					<div class="flex gap-2">
						{#if selectedReport.pdfPath}
							<Button variant="outline" size="sm">
								<FileText class="h-4 w-4 mr-2" />
								Download PDF
							</Button>
						{/if}
						{#if selectedReport.csvPath}
							<Button variant="outline" size="sm">
								<FileSpreadsheet class="h-4 w-4 mr-2" />
								Download CSV
							</Button>
						{/if}
					</div>
				</div>

				<div class="grid grid-cols-2 md:grid-cols-4 gap-4">
					<div>
						<p class="text-sm text-muted-foreground">Generated At</p>
						<p class="font-medium">{formatDate(selectedReport.generatedAt)}</p>
					</div>
					<div>
						<p class="text-sm text-muted-foreground">Generated By</p>
						<p class="font-medium">{selectedReport.generatedBy || 'System'}</p>
					</div>
					<div>
						<p class="text-sm text-muted-foreground">Findings Count</p>
						<p class="font-medium">{selectedReport.findings?.length || 0}</p>
					</div>
					<div>
						<p class="text-sm text-muted-foreground">Created</p>
						<p class="font-medium">{formatDateShort(selectedReport.createdAt)}</p>
					</div>
				</div>

				{#if selectedReport.errorMessage}
					<Alert variant="destructive">
						<AlertCircle class="h-4 w-4" />
						<AlertDescription>{selectedReport.errorMessage}</AlertDescription>
					</Alert>
				{/if}

				{#if selectedReport.findings && selectedReport.findings.length > 0}
					<div>
						<h3 class="text-lg font-semibold mb-3">Findings</h3>
						<div class="space-y-2">
							{#each selectedReport.findings as finding}
								<Alert>
									<AlertCircle class="h-4 w-4" />
									<AlertDescription>{finding}</AlertDescription>
								</Alert>
							{/each}
						</div>
					</div>
				{/if}

				{#if selectedReport.reportData}
					<div>
						<h3 class="text-lg font-semibold mb-3">Report Data</h3>
						<pre
							class="bg-muted p-4 rounded-lg overflow-auto text-xs">{JSON.stringify(
								selectedReport.reportData,
								null,
								2
							)}</pre>
					</div>
				{/if}
			</div>
		</Card>
	{:else}
		<!-- Overview: Reports List and Schedules -->
		<Tabs.Root value="reports" class="w-full">
			<Tabs.List class="grid w-full grid-cols-2">
				<Tabs.Trigger value="reports">Reports</Tabs.Trigger>
				<Tabs.Trigger value="schedules">Schedules</Tabs.Trigger>
			</Tabs.List>

			<!-- Reports Tab -->
			<Tabs.Content value="reports" class="space-y-4">
				<!-- Filters -->
				<Card class="p-4">
					<div class="flex items-center gap-4">
						<div class="flex-1">
							<Select
								value={selectedReportType as any}
								onValueChange={(value: any) => handleReportTypeChange(value)}
							>
								<SelectTrigger class="w-full">
									<SelectValue placeholder="Select report type" />
								</SelectTrigger>
								<SelectContent>
									{#each reportTypes as type}
										<SelectItem value={type.value}>{type.label}</SelectItem>
									{/each}
								</SelectContent>
							</Select>
						</div>
					</div>
				</Card>

				<!-- Reports List -->
				{#if reports.length === 0}
					<Card class="p-8">
						<div class="text-center text-muted-foreground">
							<FileText class="h-12 w-12 mx-auto mb-3 opacity-50" />
							<p>No compliance reports found</p>
						</div>
					</Card>
				{:else}
					<div class="space-y-3">
						{#each reports as report}
							<Card class="p-4 hover:bg-muted/50 transition-colors">
								<div class="flex items-start justify-between gap-4">
									<div class="flex-1">
										<div class="flex items-center gap-2 mb-2">
											<Badge variant={getReportTypeVariant(report.reportType)}>
												{report.reportType}
											</Badge>
											<Badge variant={getStatusVariant(report.status)}>
												{report.status}
											</Badge>
											{#if report.findings && report.findings.length > 0}
												<Badge variant="outline">
													<AlertCircle class="h-3 w-3 mr-1" />
													{report.findings.length} findings
												</Badge>
											{/if}
										</div>

										<div class="grid grid-cols-2 md:grid-cols-4 gap-4 text-sm">
											<div>
												<p class="text-muted-foreground">Report ID</p>
												<p class="font-medium">#{report.id.slice(0, 8)}</p>
											</div>
											<div>
												<p class="text-muted-foreground">Period</p>
												<p class="font-medium">
													{formatDateShort(report.periodStart)} - {formatDateShort(report.periodEnd)}
												</p>
											</div>
											<div>
												<p class="text-muted-foreground">Generated</p>
												<p class="font-medium">{formatDate(report.generatedAt)}</p>
											</div>
											<div>
												<p class="text-muted-foreground">Generated By</p>
												<p class="font-medium">{report.generatedBy || 'System'}</p>
											</div>
										</div>

										{#if report.errorMessage}
											<Alert variant="destructive" class="mt-3">
												<AlertCircle class="h-4 w-4" />
												<AlertDescription>{report.errorMessage}</AlertDescription>
											</Alert>
										{/if}
									</div>

									<div class="flex flex-col gap-2">
										{#if report.pdfPath}
											<Button variant="outline" size="sm">
												<FileText class="h-4 w-4 mr-2" />
												PDF
											</Button>
										{/if}
										{#if report.csvPath}
											<Button variant="outline" size="sm">
												<FileSpreadsheet class="h-4 w-4 mr-2" />
												CSV
											</Button>
										{/if}
									</div>
								</div>
							</Card>
						{/each}
					</div>
				{/if}
			</Tabs.Content>

			<!-- Schedules Tab -->
			<Tabs.Content value="schedules" class="space-y-4">
				{#if schedules.length === 0}
					<Card class="p-8">
						<div class="text-center text-muted-foreground">
							<Calendar class="h-12 w-12 mx-auto mb-3 opacity-50" />
							<p>No report schedules configured</p>
						</div>
					</Card>
				{:else}
					<div class="space-y-3">
						{#each schedules as schedule}
							<Card class="p-4">
								<div class="space-y-4">
									<div class="flex items-start justify-between">
										<div>
											<div class="flex items-center gap-2 mb-2">
												<Badge variant={getReportTypeVariant(schedule.reportType)}>
													{schedule.reportType}
												</Badge>
												<Badge variant={schedule.enabled ? 'default' : 'outline'}>
													{schedule.enabled ? 'Enabled' : 'Disabled'}
												</Badge>
											</div>
											<p class="text-sm text-muted-foreground">Schedule ID: {schedule.id}</p>
										</div>
										<Shield class="h-5 w-5 text-muted-foreground" />
									</div>

									<div class="grid grid-cols-2 md:grid-cols-4 gap-4 text-sm">
										<div>
											<p class="text-muted-foreground flex items-center gap-1">
												<Clock class="h-3 w-3" />
												Cron Schedule
											</p>
											<p class="font-mono font-medium">{schedule.scheduleCron}</p>
										</div>
										<div>
											<p class="text-muted-foreground">Last Run</p>
											<p class="font-medium">
												{schedule.lastRunAt ? formatDate(schedule.lastRunAt) : 'Never'}
											</p>
										</div>
										<div>
											<p class="text-muted-foreground">Next Run</p>
											<p class="font-medium">
												{schedule.nextRunAt ? formatDate(schedule.nextRunAt) : 'N/A'}
											</p>
										</div>
										<div>
											<p class="text-muted-foreground flex items-center gap-1">
												<User class="h-3 w-3" />
												Created By
											</p>
											<p class="font-medium">{schedule.createdBy || 'System'}</p>
										</div>
									</div>

									{#if schedule.recipients && schedule.recipients.length > 0}
										<div>
											<p class="text-sm text-muted-foreground mb-2">Recipients</p>
											<div class="flex flex-wrap gap-2">
												{#each schedule.recipients as recipient}
													<Badge variant="outline">{recipient}</Badge>
												{/each}
											</div>
										</div>
									{/if}
								</div>
							</Card>
						{/each}
					</div>
				{/if}
			</Tabs.Content>
		</Tabs.Root>
	{/if}
</div>
