---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sveltehr-ingress
  namespace: sveltehr-dev
  annotations:
    nginx.ingress.kubernetes.io/rate-limit: '1000' # Higher limit for dev
spec:
  rules:
    - host: localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sveltehr-frontend
                port:
                  number: 3000
          - path: /graphql
            pathType: Prefix
            backend:
              service:
                name: sveltehr-backend
                port:
                  number: 4000
