[[bin]]
path = "src/main.rs"
name = "hr-graphql-server"
plugin = false
proc-macro = false
edition = "2021"
required-features = []

[[test]]
path = "tests/contract_tests.rs"
name = "contract_tests"
plugin = false
proc-macro = false
edition = "2021"
required-features = []

[package]
name = "hr-graphql-server"
edition = "2021"
version = "0.0.1"

[dependencies]
anyhow = "1.0"
async-graphql-axum = "7.0"
async-trait = "0.1"
axum = "0.8"
base64 = "0.22"
bcrypt = "0.15"
dataloader = "0.17"
dotenv = "0.15"
envy = "0.4"
futures = "0.3"
http-body-util = "0.1"
jsonwebtoken = "9.0"
rust_decimal = "1.35"
serde_json = "1.0"
thiserror = "1.0"
tracing = "0.1"

[dependencies.async-graphql]
version = "7.0"
features = ["chrono", "uuid", "dataloader", "boxed-trait"]

[dependencies.chrono]
version = "0.4"
features = ["serde"]

[dependencies.sea-orm]
version = "0.12"
features = ["sqlx-postgres", "runtime-tokio-rustls", "macros"]

[dependencies.serde]
version = "1.0"
features = ["derive"]



[dependencies.tokio]
version = "1"
features = ["full"]

[dependencies.tower]
version = "=0.4.13"
features = ["util"]

[dependencies.tower-http]
version = "0.5"
features = ["cors", "trace"]

[dependencies.tracing-subscriber]
version = "0.3"
features = ["env-filter"]

[dependencies.uuid]
version = "1.0"
features = ["serde", "v4"]

[build-dependencies]
sea-orm-codegen = "1.1.17"

[lib]
path = "src/lib.rs"
name = "hr_graphql_server"
plugin = false
proc-macro = false
edition = "2021"
required-features = []
crate-type = ["lib"]
