version: 3
endpoint: http://localhost:8080
admin_secret: your-admin-secret-here
metadata_directory: metadata
actions:
  kind: synchronous
  handler_webhook_baseurl: http://localhost:3001
migrations_directory: ../migrations
seeds_directory: ../seeds