/**
 * Data Generator Service
 *
 * Generates realistic sample data using Faker.js with deterministic seeding
 * for cross-machine consistency. Supports custom field generators and
 * naming patterns.
 */

import { faker } from '@faker-js/faker';
import { TableConfig } from '../models/SampleDataConfig';
import { TableSchema, ColumnSchema } from '../models/DatabaseSchema';
import { DataGenerationError } from '../models/Errors';
import { ForeignKeyResolver } from './ForeignKeyResolver';

/**
 * Generated record type.
 */
export type GeneratedRecord = Record<string, any>;

/**
 * Custom field generator function.
 */
export type FieldGenerator = (record: GeneratedRecord, index: number) => any;

/**
 * Data generator service for creating sample data.
 */
export class DataGenerator {
  private currentSeed: number | null = null;
  private foreignKeyResolver: ForeignKeyResolver | null = null;

  /**
   * Sets the random seed for deterministic generation.
   *
   * @param seed - Seed value
   */
  setSeed(seed: number): void {
    this.currentSeed = seed;
    faker.seed(seed);
  }

  /**
   * Sets the foreign key resolver for handling FK relationships.
   *
   * @param resolver - Foreign key resolver instance
   */
  setForeignKeyResolver(resolver: ForeignKeyResolver): void {
    this.foreignKeyResolver = resolver;
  }

  /**
   * Generates sample data for a table.
   *
   * @param tableSchema - Table schema information
   * @param tableConfig - Table configuration
   * @param count - Number of records to generate
   * @param schemaName - Database schema name for FK resolution
   * @param startIndex - Starting index for record numbering
   * @returns Array of generated records
   */
  async generateRecords(
    tableSchema: TableSchema,
    tableConfig: TableConfig,
    count: number,
    schemaName: string,
    startIndex = 0
  ): Promise<GeneratedRecord[]> {
    const records: GeneratedRecord[] = [];

    // Pre-cache foreign keys if resolver is available
    if (this.foreignKeyResolver && tableSchema.foreignKeys.length > 0) {
      await this.foreignKeyResolver.preCacheForeignKeys(tableSchema.foreignKeys, schemaName);
    }

    for (let i = 0; i < count; i++) {
      const index = startIndex + i;
      try {
        const record = await this.generateRecord(tableSchema, tableConfig, index, schemaName);
        records.push(record);
      } catch (error) {
        throw new DataGenerationError(
          `Failed to generate record at index ${index}: ${error instanceof Error ? error.message : String(error)}`,
          tableSchema.tableName,
          index
        );
      }
    }

    return records;
  }

  /**
   * Generates a single record.
   *
   * @param tableSchema - Table schema information
   * @param tableConfig - Table configuration
   * @param index - Record index
   * @param schemaName - Database schema name for FK resolution
   * @returns Generated record
   */
  private async generateRecord(
    tableSchema: TableSchema,
    tableConfig: TableConfig,
    index: number,
    schemaName: string
  ): Promise<GeneratedRecord> {
    const record: GeneratedRecord = {};

    // Generate values for each column
    for (const column of tableSchema.columns) {
      // Skip auto-generated columns (like serial primary keys)
      if (this.isAutoGeneratedColumn(column)) {
        continue;
      }

      // Check for custom field generator
      if (column.columnName in tableConfig.customFields) {
        const customGenerator = tableConfig.customFields[column.columnName];
        if (typeof customGenerator === 'function') {
          record[column.columnName] = customGenerator(record, index);
        } else if (customGenerator === 'SEQUENTIAL_FK') {
          // Special value: assign sequential FK values (index + 1)
          record[column.columnName] = index + 1;
        } else if (typeof customGenerator === 'string') {
          // Process string patterns with {id}, {id:N}, {index} placeholders
          record[column.columnName] = this.applyNamingPattern(customGenerator, index);
        } else {
          // Use the value as-is (including null, numbers, booleans, etc.)
          record[column.columnName] = customGenerator;
        }
        continue;
      }

      // Check if this is a foreign key column
      if (this.foreignKeyResolver && this.foreignKeyResolver.isForeignKey(tableSchema.foreignKeys, column.columnName)) {
        const nullProbability = column.isNullable ? 0.2 : 0;
        record[column.columnName] = await this.foreignKeyResolver.resolveForeignKeyByColumn(
          tableSchema.foreignKeys,
          column.columnName,
          schemaName,
          nullProbability
        );
        continue;
      }

      // Generate value based on column type and name
      record[column.columnName] = this.generateColumnValue(column, tableConfig, index);
    }

    return record;
  }

  /**
   * Generates a value for a column.
   *
   * @param column - Column schema
   * @param tableConfig - Table configuration
   * @param index - Record index
   * @returns Generated value
   */
  private generateColumnValue(column: ColumnSchema, tableConfig: TableConfig, index: number): any {
    // Handle nullable columns
    if (column.isNullable && faker.datatype.boolean({ probability: 0.1 })) {
      return null;
    }

    // Generate based on column name patterns first (before default values)
    const value = this.generateByColumnName(column, tableConfig, index);
    if (value !== undefined) {
      return value;
    }

    // Handle default values (skip function calls - those are database-generated)
    if (column.defaultValue && faker.datatype.boolean({ probability: 0.2 })) {
      const parsedDefault = this.parseDefaultValue(column.defaultValue);
      if (parsedDefault !== undefined) {
        return parsedDefault;
      }
    }

    // Generate based on data type
    return this.generateByDataType(column, index);
  }

  /**
   * Generates value based on column name.
   *
   * @param column - Column schema
   * @param tableConfig - Table configuration
   * @param index - Record index
   * @returns Generated value or undefined if no pattern matched
   */
  private generateByColumnName(
    column: ColumnSchema,
    tableConfig: TableConfig,
    index: number
  ): any {
    const name = column.columnName.toLowerCase();

    // Email patterns
    if (name.includes('email')) {
      return this.generateEmail(tableConfig, index);
    }

    // Name patterns
    if (name === 'full_name' || name === 'name') {
      return this.applyNamingPattern(tableConfig.namingPattern, index);
    }
    if (name === 'first_name') {
      return faker.person.firstName();
    }
    if (name === 'last_name') {
      return faker.person.lastName();
    }

    // Phone patterns
    if (name.includes('phone')) {
      return faker.phone.number();
    }

    // Address patterns
    if (name.includes('address')) {
      return faker.location.streetAddress();
    }
    if (name.includes('city')) {
      return faker.location.city();
    }
    if (name.includes('state')) {
      return faker.location.state();
    }
    if (name.includes('zip') || name.includes('postal')) {
      return faker.location.zipCode();
    }
    if (name.includes('country')) {
      return faker.location.country();
    }

    // Role level pattern (specific constraint values)
    if (name === 'role_level') {
      return faker.helpers.arrayElement([0, 20, 60, 80, 100]);
    }

    // Date patterns
    if (name.includes('birth') && name.includes('date')) {
      return faker.date.birthdate();
    }
    if (name.includes('hire') && name.includes('date')) {
      return faker.date.past({ years: 5 });
    }

    // Salary/compensation patterns
    if (name.includes('salary')) {
      return faker.number.int({ min: 40000, max: 200000 });
    }

    // Description/notes patterns
    if (name.includes('description') || name.includes('notes')) {
      return faker.lorem.paragraph();
    }

    // Status patterns - handle enum types specially
    if (name.includes('status')) {
      // Check if this is a USER-DEFINED type (enum)
      if (column.dataType === 'USER-DEFINED') {
        // This is an enum type - use uppercase values
        if (name === 'status') {
          return faker.helpers.arrayElement(['ACTIVE', 'INACTIVE', 'ON_LEAVE', 'TERMINATED']);
        }
        // Default uppercase for other enum status types
        return faker.helpers.arrayElement(['ACTIVE', 'INACTIVE', 'PENDING']);
      }
      // Generic status field (lowercase for text columns)
      return faker.helpers.arrayElement(['active', 'inactive', 'pending']);
    }

    // Currency patterns
    if (name.includes('currency')) {
      return faker.finance.currencyCode(); // Returns 3-letter ISO codes like 'USD', 'EUR'
    }

    // Boolean patterns
    if (name.includes('is_') || name.includes('has_')) {
      return faker.datatype.boolean();
    }

    return undefined;
  }

  /**
   * Generates value based on data type.
   *
   * @param column - Column schema
   * @param index - Record index
   * @returns Generated value
   */
  private generateByDataType(column: ColumnSchema, index: number): any {
    const dataType = column.dataType.toLowerCase();

    // String types
    if (dataType.includes('char') || dataType.includes('text')) {
      const maxLength = column.maxLength ?? 255;
      return faker.lorem.words(Math.min(3, Math.floor(maxLength / 10)));
    }

    // Integer types
    if (dataType.includes('int') || dataType.includes('serial')) {
      return faker.number.int({ min: 1, max: 1000000 });
    }

    // Numeric/decimal types
    if (dataType.includes('numeric') || dataType.includes('decimal') || dataType.includes('real')) {
      return faker.number.float({ min: 0, max: 100000, multipleOf: 0.01 });
    }

    // Boolean type
    if (dataType.includes('bool')) {
      return faker.datatype.boolean();
    }

    // Date types
    if (dataType.includes('date')) {
      return faker.date.past({ years: 2 });
    }

    // Timestamp types
    if (dataType.includes('timestamp')) {
      return faker.date.recent();
    }

    // UUID type
    if (dataType.includes('uuid')) {
      return faker.string.uuid();
    }

    // JSON type
    if (dataType.includes('json')) {
      return JSON.stringify({ data: faker.lorem.words() });
    }

    // Default to string
    return faker.lorem.word();
  }

  /**
   * Applies naming pattern to generate a name.
   *
   * @param pattern - Naming pattern (e.g., "Sample User {id}" or "Sample User {id:3}")
   * @param index - Record index
   * @returns Generated name
   */
  private applyNamingPattern(pattern: string, index: number): string {
    // Replace {id:N} pattern with N-digit padded ID
    let result = pattern.replace(/\{id:(\d+)\}/g, (_, digits) => {
      return String(index + 1).padStart(parseInt(digits, 10), '0');
    });

    // Replace {id} pattern with 3-digit padded ID (default)
    result = result.replace(/\{id\}/g, String(index + 1).padStart(3, '0'));

    // Replace {index} pattern with raw index
    result = result.replace(/\{index\}/g, String(index + 1));

    return result;
  }

  /**
   * Generates an email based on naming pattern.
   *
   * @param tableConfig - Table configuration
   * @param index - Record index
   * @returns Generated email
   */
  private generateEmail(tableConfig: TableConfig, index: number): string {
    const name = this.applyNamingPattern(tableConfig.namingPattern, index);
    const emailName = name
      .toLowerCase()
      .replace(/\s+/g, '.')
      .replace(/[^a-z0-9.]/g, '');

    const paddedId = String(index + 1).padStart(3, '0');
    return `${emailName.split(' ')[0]}.${emailName.split(' ')[1] || 'user'}.${paddedId}@example.com`;
  }

  /**
   * Generates a full name.
   */
  generateFullName(): string {
    return faker.person.fullName();
  }

  /**
   * Generates an email address.
   */
  generateEmail(): string {
    return faker.internet.email();
  }

  /**
   * Generates a phone number.
   */
  generatePhoneNumber(): string {
    return faker.phone.number();
  }

  /**
   * Generates a date.
   */
  generateDate(): Date {
    return faker.date.past();
  }

  /**
   * Generates a random integer.
   */
  generateInteger(min = 0, max = 1000): number {
    return faker.number.int({ min, max });
  }

  /**
   * Generates a random boolean.
   */
  generateBoolean(): boolean {
    return faker.datatype.boolean();
  }

  /**
   * Checks if a column is auto-generated.
   *
   * @param column - Column schema
   * @returns True if column is auto-generated
   */
  private isAutoGeneratedColumn(column: ColumnSchema): boolean {
    // Generated (computed) columns - ALWAYS skip these
    if (column.isGenerated) {
      return true;
    }

    // Serial/sequence columns
    if (column.dataType.includes('serial') || column.dataType.includes('sequence')) {
      return true;
    }

    // Columns with nextval default
    if (column.defaultValue && column.defaultValue.includes('nextval')) {
      return true;
    }

    // UUID columns with default gen_random_uuid()
    if (
      column.dataType.includes('uuid') &&
      column.defaultValue &&
      column.defaultValue.includes('gen_random_uuid')
    ) {
      return true;
    }

    // Timestamp columns with NOW() or CURRENT_TIMESTAMP default (but only for created_at/updated_at)
    if (
      (column.columnName === 'created_at' || column.columnName === 'updated_at') &&
      column.defaultValue &&
      (column.defaultValue.includes('NOW()') || column.defaultValue.includes('CURRENT_TIMESTAMP'))
    ) {
      return true;
    }

    return false;
  }

  /**
   * Parses a default value string.
   *
   * @param defaultValue - Default value string from database
   * @returns Parsed value
   */
  private parseDefaultValue(defaultValue: string): any {
    // Skip function calls - they should be handled by the database
    if (defaultValue.includes('()') || defaultValue.includes('nextval') || defaultValue.includes('NOW')) {
      return undefined; // Will cause column value to be generated instead
    }

    // Remove PostgreSQL enum casting syntax like 'ACTIVE'::hr_public.employee_status
    // This regex removes everything from :: to the end
    let cleaned = defaultValue.replace(/::[a-z_0-9.]+$/i, '');

    // Boolean values
    if (cleaned === 'true') return true;
    if (cleaned === 'false') return false;

    // Numeric values
    if (/^-?\d+(\.\d+)?$/.test(cleaned)) {
      return parseFloat(cleaned);
    }

    // String values (remove quotes)
    if (/^'.*'$/.test(cleaned)) {
      return cleaned.slice(1, -1);
    }

    // Default to string
    return cleaned;
  }

  /**
   * Gets the current seed value.
   */
  getCurrentSeed(): number | null {
    return this.currentSeed;
  }
}
