import { PERMISSIONS } from '$lib/auth/rbac';

// Route-permission mappings
export const ROUTE_PERMISSIONS: Record<string, string[]> = {
	'/admin': [PERMISSIONS.ADMIN_ALL],
	'/hr': [PERMISSIONS.EMPLOYEES_READ_ALL],
	'/hr/employees': [PERMISSIONS.EMPLOYEES_READ_ALL],
	'/hr/employees/create': [PERMISSIONS.EMPLOYEES_WRITE],
	'/hr/departments': [PERMISSIONS.DEPARTMENTS_READ_ALL],
	'/hr/reports': [PERMISSIONS.REPORTS_READ_ALL],
	'/dashboard': [], // Generally accessible
	'/profile': [] // User's own profile
};

// Permission suggestions based on role
export const ROLE_PERMISSION_SUGGESTIONS: Record<string, string[]> = {
	admin: [PERMISSIONS.ADMIN_ALL],
	administrator: [PERMISSIONS.ADMIN_ALL],
	'hr manager': [
		PERMISSIONS.EMPLOYEES_MANAGE,
		PERMISSIONS.DEPARTMENTS_MANAGE,
		PERMISSIONS.REPORTS_READ_ALL,
		PERMISSIONS.PERFORMANCE_MANAGE,
		PERMISSIONS.LEAVE_APPROVE,
		PERMISSIONS.PAYROLL_READ_ALL
	],
	hr_manager: [
		PERMISSIONS.EMPLOYEES_MANAGE,
		PERMISSIONS.DEPARTMENTS_MANAGE,
		PERMISSIONS.REPORTS_READ_ALL,
		PERMISSIONS.PERFORMANCE_MANAGE,
		PERMISSIONS.LEAVE_APPROVE,
		PERMISSIONS.PAYROLL_READ_ALL
	],
	manager: [
		PERMISSIONS.EMPLOYEES_READ_TEAM,
		PERMISSIONS.DEPARTMENTS_READ_ALL,
		PERMISSIONS.REPORTS_READ_TEAM,
		PERMISSIONS.PERFORMANCE_READ_TEAM,
		PERMISSIONS.LEAVE_APPROVE
	],
	employee: [
		PERMISSIONS.EMPLOYEES_READ_SELF,
		PERMISSIONS.DEPARTMENTS_READ_SELF,
		PERMISSIONS.LEAVE_WRITE
	]
};

// Default suggestions if role not found
export const DEFAULT_PERMISSION_SUGGESTIONS = [PERMISSIONS.EMPLOYEES_READ_SELF];
